version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: storage
    volumes:
      - ./sampleDB:/data/dump
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    ports:
      - '27017:27017'

volumes:
  sampleDB: